"""phase4 governance: prompt_versions + model_routing

Revision ID: 1a9145015fe0
Revises: 0001_initial
Create Date: 2026-06-15 15:01:03.944401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a9145015fe0'
down_revision: Union[str, Sequence[str], None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_routing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task', sa.String(length=50), nullable=False),
    sa.Column('champion', sa.String(length=20), nullable=False),
    sa.Column('challenger', sa.String(length=20), nullable=True),
    sa.Column('canary_pct', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task')
    )
    op.create_table('prompt_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scorecard', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_index(op.f('ix_enc_patient'), table_name='encounters')
    op.drop_index(op.f('ix_enc_provider'), table_name='encounters')
    op.drop_index(op.f('ix_icd_vec'), table_name='icd10_codes', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('uq_patients_identity'), table_name='patients')
    op.drop_constraint(op.f('templates_created_by_fkey'), 'templates', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('templates_created_by_fkey'), 'templates', 'users', ['created_by'], ['id'])
    op.create_index(op.f('uq_patients_identity'), 'patients', [sa.literal_column('lower(first_name::text)'), sa.literal_column('lower(last_name::text)'), 'dob'], unique=True)
    op.create_index(op.f('ix_icd_vec'), 'icd10_codes', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_enc_provider'), 'encounters', ['provider_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_enc_patient'), 'encounters', ['patient_id'], unique=False)
    op.drop_table('prompt_versions')
    op.drop_table('model_routing')
    # ### end Alembic commands ###
